"""Added username column to monthrecord and monthstat

Revision ID: 6f43ccfc8132
Revises: 00d94264d14d
Create Date: 2024-10-29 11:54:19.815678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f43ccfc8132'
down_revision: Union[str, None] = '00d94264d14d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('month_record', sa.Column('username', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'month_record', 'user', ['username'], ['username'])
    op.add_column('month_stat', sa.Column('username', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'month_stat', 'user', ['username'], ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'month_stat', type_='foreignkey')
    op.drop_column('month_stat', 'username')
    op.drop_constraint(None, 'month_record', type_='foreignkey')
    op.drop_column('month_record', 'username')
    # ### end Alembic commands ###
