"""Added foreign key to User table

Revision ID: e9f362fd32fa
Revises: 00d94264d14d
Create Date: 2024-10-24 23:56:23.349185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9f362fd32fa'
down_revision: Union[str, None] = '00d94264d14d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('month_record', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'month_record', 'user', ['user_id'], ['id'])
    op.add_column('month_stat', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'month_stat', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'month_stat', type_='foreignkey')
    op.drop_column('month_stat', 'user_id')
    op.drop_constraint(None, 'month_record', type_='foreignkey')
    op.drop_column('month_record', 'user_id')
    # ### end Alembic commands ###
