version: "3.8"
services:
  budget-api:
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    build: .
    links:
      - db
    ports:
      - "5001:5001"
    volumes:
      - .:/Budget_API

  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=pwd
      - MYSQL_ROOT_PASSWORD=pwd
    ports:
      - "32000:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
